module.exports = {
  cliente: {
    nome: "Economy Assessoria — Marketing",
    subdomain: "economy-mkt-bi",
    coolify_app_uuid: "wk8h1fk2jnklo7mf3ksa06ig",
    cor_primaria: "#f59e0b",
  },
  fontes: {
    adapters: ["economy-xlsx"],
    economy_xlsx: {
      files: [
        "Economy Bahia - Caixa Real.xlsx",
        "Economy Brasília - Caixa Real.xlsx",
        "Economy Ceará - Caixa Real.xlsx",
        "Economy Goiás - Caixa Real.xlsx",
        "Economy Maranhão - Caixa Real.xlsx",
        "Economy Online - Caixa Real.xlsx",
        "Economy Pará - Caixa Real.xlsx",
        "Economy Paraná - Caixa Real.xlsx",
        "Economy Taguatinga - Caixa Real.xlsx",
      ],
      vendas_path: "G:/Meu Drive/BGP/CLIENTES/BI/450.  ECONOMY ASSESSORIA/BASES/Vendas",
      vendas_files: [
        "Economy Brasília - Vendas - 2025_a_2026.xlsx",
        "Economy Bahia - Vendas e Cancelamentos.xlsx",
        "Economy Brasília - Vendas e Cancelamentos.xlsx",
        "Economy Ceará - Vendas e Cancelamentos.xlsx",
        "Economy Goiás - Vendas e Cancelamentos.xlsx",
        "Economy Maranhão - Vendas e Cancelamentos.xlsx",
        "Economy Online - Vendas e Cancelamentos.xlsx",
        "Economy Pará - Vendas e Cancelamentos.xlsx",
        "Economy Paraná - Vendas e Cancelamentos.xlsx",
        "Nirocred - Vendas e Cancelamentos.xlsx",
        "Boleto Amigo - Vendas e Cancelamentos.xlsx",
      ],
      vendedores_file: "Economy Brasilia - Dimensao Vendedores.xlsx",
      cancelamentos_file: "G:/Meu Drive/BGP/CLIENTES/BI/450.  ECONOMY ASSESSORIA/BASES/Cancelamentos Vendas/CONSOLIDADO - Cancelamentos Vendas.xlsx",
      rd_station_file: "G:/Meu Drive/BGP/CLIENTES/BI/450.  ECONOMY ASSESSORIA/BASES/base_rd.xlsx",
    },
    drive: {
      base_path: "G:/Meu Drive/BGP/CLIENTES/BI/450.  ECONOMY ASSESSORIA/BASES/Por Empresa v2",
    },
  },
  pages: {
    geral: {
      overview: "hidden",
      receita: "hidden",
      despesa: "hidden",
      fluxo: "hidden",
      tesouraria: "hidden",
      comparativo: "hidden",
      relatorio: "hidden",
      valuation: "hidden",
      orcamento: "hidden",
      dre: "hidden",
    },
    outros: {
      indicators: "hidden",
      faturamento_produto: "hidden",
      curva_abc: "hidden",
      marketing: "hidden",
      hierarquia: "hidden",
      detalhado: "hidden",
      profunda_cliente: "hidden",
      crm: "hidden",
      marketing_roi: "active",
      consolidado: "hidden",
      vendas: "hidden",
      cancelamentos: "hidden",
    },
  },
  meta: {
    ano_corrente: 2026,
    metas_crm: { mes: 0, ano: 0 },
    valuation_premissas: { wacc: 25, growth_year2: 20, growth_year3: 20, ipca: 4.5, perpetuity_growth: 10 },
  },
  template: { version_when_created: "1.0.0", version_last_synced: "1.0.0" },
};
